"""Augmentation de la limite de la longueur des messages

Revision ID: 7179dbf65294
Revises: 785d14d28685
Create Date: 2026-03-01 16:07:09.706334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7179dbf65294'
down_revision: Union[str, Sequence[str], None] = '785d14d28685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=2000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###
