"""
ARIA — Auto-generated Tool
Tool name  : extract_from_excel_advanced
Description: Extract data from Excel with multiple sheets and apply filters
Generated  : 2026-02-28T12:10:10.529936

WARNING: Auto-generated by ARIA Tool Builder. Do not edit manually.
"""

from __future__ import annotations

def extract_from_excel_advanced(input_data):
    """
    Extract data from an Excel file and apply column filtering.

    Args:
        input_data (dict): Dictionary with the following keys:
            - path (str): Path to the Excel file.
            - sheet_name (str): Name of the sheet to extract.
            - filter_column (str): Column to filter on.
            - filter_value (str): Value to match in the filter column.

    Returns:
        dict: Dictionary containing:
            - rows (list): List of rows that match the filter, each row as a list of cell values.
            - columns (list): List of column names.
            - filtered_count (int): Number of rows returned after filtering.
    """
    import os
    import pandas as pd

    try:
        path = input_data["path"]
        sheet_name = input_data["sheet_name"]
        filter_column = input_data["filter_column"]
        filter_value = input_data["filter_value"]

        if not os.path.isfile(path):
            raise FileNotFoundError(f"Excel file not found: {path}")

        df = pd.read_excel(path, sheet_name=sheet_name, engine="openpyxl")

        if df.empty:
            return {"rows": [], "columns": [], "filtered_count": 0}

        if filter_column not in df.columns:
            raise KeyError(f"Column '{filter_column}' not found in sheet '{sheet_name}'")

        filtered_df = df[df[filter_column].astype(str).eq(str(filter_value))]

        rows = filtered_df.astype(str).values.tolist()
        columns = filtered_df.columns.tolist()
        filtered_count = len(rows)

        return {"rows": rows, "columns": columns, "filtered_count": filtered_count}

    except FileNotFoundError as e:
        return {"error": str(e)}
    except ValueError as e:
        # pandas raises ValueError for invalid sheet name
        return {"error": str(e)}
    except KeyError as e:
        return {"error": str(e)}
    except Exception as e:
        return {"error": f"Unexpected error: {e}"}
