"""
Tool Builder — Code Generation Utilities
Fonctions utilitaires pour construire les prompts et le fichier final.
"""

from __future__ import annotations

import json
from datetime import datetime

from agent.global_variable.tool_generation_prompt import (
    TOOL_GENERATION_PROMPT,
    TOOL_FIX_PROMPT,
)


TOOL_FILE_TEMPLATE = '''"""
ARIA — Auto-generated Tool
Tool name  : {tool_name}
Description: {description}
Generated  : {generated_at}

WARNING: Auto-generated by ARIA Tool Builder. Do not edit manually.
"""

from __future__ import annotations

{code}
'''


def build_generation_prompt(tool_spec: dict) -> str:
    return TOOL_GENERATION_PROMPT.format(
        tool_spec=json.dumps(tool_spec, indent=2, ensure_ascii=False)
    )


def build_fix_prompt(tool_spec: dict, generated_code: str, test_error: str) -> str:
    return TOOL_FIX_PROMPT.format(
        tool_spec=json.dumps(tool_spec, indent=2, ensure_ascii=False),
        generated_code=generated_code,
        test_error=test_error,
    )


def build_tool_file(tool_name: str, description: str, code: str) -> str:
    return TOOL_FILE_TEMPLATE.format(
        tool_name=tool_name,
        description=description,
        code=code,
        generated_at=datetime.utcnow().isoformat(),
    )